---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
      exclude_fingerprints:
      - a308e38bf3f3a0db3f248490dd813c52
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths: []
