engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 65
        php:
          mass_threshold: 85
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CyclomaticComplexity:
        enabled: false
      UnusedLocalVariable:
        enabled: false
    config:
      rulesets: "codesize,design,unusedcode"
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- cs/
- mister42/assets/
- mister42/commands/
- mister42/messages/
