---
engines:
  duplication:
    enabled: true
    checks:
      Identical code:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths: []
