build:
    environment:
        php:
            version: 7.4
            compile_options: '--enable-gd'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            command: "true"
filter:
    dependency_paths:
        - "vendor/"
    excluded_paths:
        - "cs/"
        - "mister42/tests/"
        - "mr42/tests/"
tools:
    php_cs_fixer:
        config: { level: psr2 }
