build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            command: "true"
filter:
    dependency_paths:
        - "$HOME/vendor"
    excluded_paths:
        - "cs/"
        - "tests/"
tools:
    php_cs_fixer:
        config: { level: psr2 }
